export { ArticleRatingLazy as ArticleRating } from './ui/ArticleRating.lazy'
export type { ArticleRatingSchema } from './model/types/articleRatingSchema'
export { articleRatingReducer } from './model/slice/articleRatingSlice'
export { getArticleRating } from './model/services/getArticleRating/getArticleRating'
export { updateArticleRating } from './model/services/updateArticleRating/updateArticleRating'
