export { ArticleAddCommentLazy as ArticleAddComment } from './ui/ArticleAddComment/ArticleAddComment.lazy'
export type { ArticleCommentSchema } from './model/types/articleCommentSchema'
export { getArticleComments } from './model/services/gerArticleComments/getArticleComments'
export { articleCommentsReducer } from './model/slice/articleCommentSlice'
export { ArticleCommentContainer } from './ui/ArticleCommentContainer/ArticleCommentContainer'
